name: ghflutter
description: GitHub Flutter app.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
